### ISSUE TITLE
Help supporting AXi PSUs

### ISSUE THREAD

**Issue by MJDSys** [wgottwalt/corsair-psu#5]
Firstly, thanks for implementing/upstreaming this driver!  I was really excited to try it, but noticed AXi support is still a WIP.  Is there anything I can do to help?  Things like USB logs, testing, or help with implementation?  My PSU is an AX1600i and I'm happy to help any way I can.  Thanks again for your work!

**Comment by wgottwalt** [comment]
Well, AXi is not even WIP. The AXi series uses a full blown USB protocol. The
data exchanged is somewhat similar to the RMi/HXi series, but is based on USB
HID. Writing a full blown USB driver is a lot more difficult (the actual USB
functionality is about 3x-5x bigger compared to USB HID). What I need is full
access to such a PSU and the Corsair Link dongle (on older models). The next
days I will get access to an AXi 860, which hopefully works out like I thought.
The AXi 860 is one of these supplies with a Corsair Link dongle, which is
connected via serial port. Your AXi 1600 should have a builtin dongle. I may
need testing against other models later if I manage to write the driver at all.

**Comment by denharad** [comment]
I have an AX1500i & would also like to help, although that's limited to testing software & sharing debug info.

**Comment by wgottwalt** [comment]
I may need testers later, but beyond that there is not much you can do.

**Comment by maximlevitsky** [comment]
I have AX1600i, I can help if I find some free time.

**Comment by bachandi** [comment]
Any news on the support of the AXi PSUs? I could not find anything regarding them in the commits.
