### ISSUE TITLE
New HX1000i revision

### ISSUE THREAD

**Issue by Gigadoc2** [wgottwalt/corsair-psu#8]
There is a new version of the HX1000i PSU, and it comes with a different USB ID (`1b1c:1c1e`). For very preliminary testing I've just added the ID to the rmi-hxi-query tool and it seems to work just fine:

```
--- CORSAIR HX1000i  CORSAIR HX1000i  (1b1c:1c1e) ---
uptime:        00:14:51
total uptime:  01:54:51
vrm temp:      40.750°C (max 70.000°C)
case temp:     38.500°C (max 70.000°C)
fan:           0.000rpm
v_in:          230.000V
v_out 12v:     12.000V (min 8.406V max 15.593V)
v_out 5v:      5.078V (min 3.500V max 6.500V)
v_out 3.3v:    3.328V (min 2.312V max 4.296V)
curr_out 12v:  3.500A (max 112.500A)
curr_out 5v:   6.562A (max 40.000A)
curr_out 3.3v: 2.687A (max 40.000A)
power 12v:     54.000W
power 5v:      33.500W
power 3v3:     8.500W
```

I don't know when I can get around to properly testing it (putting some load onto it and see if the values make sense, whether the fan value will be correct once it actually starts spinning etc.), but I wanted to let you know that this new revision exists and that - on first glance - it looks like the iCUE part works just the same as before.

**Comment by wgottwalt** [comment]
Huh, did I forget to add the total watts entry in the tool? Odd but yeah, the values look fine to me. The fan kicks in after 1/3 to 1/2 of the total watts gets drawn. And the gap between the old USB ids and the new ones tells me, there are very likely new revisions of the other PSUs as well.

**Comment by shavenne** [comment]
Just installed a new HX1500i. It has the USB ID `1b1c:1c1f` and is also working fine after adding the ID.

```
corsairpsu-hid-3-5
Adapter: HID adapter
v_in:        230.00 V  
v_out +12v:   12.03 V  (crit min =  +8.41 V, crit max = +15.59 V)
v_out +5v:     5.05 V  (crit min =  +3.50 V, crit max =  +6.50 V)
v_out +3.3v:   3.30 V  (crit min =  +2.31 V, crit max =  +4.30 V)
psu fan:        0 RPM
vrm temp:     +40.2°C  (crit = +70.0°C)
case temp:    +40.0°C  (crit = +70.0°C)
power total: 150.00 W  
power +12v:   98.00 W  
power +5v:    29.50 W  
power +3.3v:  11.00 W  
curr +12v:     8.00 A  (crit max = +168.75 A)
curr +5v:      5.88 A  (crit max = +40.00 A)
curr +3.3v:    3.44 A  (crit max = +40.00 A)
```

**Comment by wgottwalt** [comment]
Oh nice. I will also push it upstream. Do you also use this PSU under Windows? If so, does it report additional values?

**Comment by shavenne** [comment]
Actually I don't use something else beside HWinfo64 under Windows but I just installed iCUE for this little report :)

So, this is what values you get:
![corsair_1](https://user-images.githubusercontent.com/20374265/194752768-f49fb80d-e6cd-4b3a-96be-1851cb112346.png)

You can also switch between single and multi rail mode (which also was possible with my previous RM750i):
![corsair_2](https://user-images.githubusercontent.com/20374265/194752797-34048184-d5f6-4c0f-9c50-2c356a609cef.png)

And you can set a custom fan curve or fixed speed (I don't know if this was possible with my RM750i):
![corsair_3](https://user-images.githubusercontent.com/20374265/194752832-26e6cabb-522b-460d-850c-770039b5beb8.png)
Tested this with 100% and it was even saved after power loss so it seems to be persistent.

This is what HWinfo64 is showing:
![corsair_hwinfo](https://user-images.githubusercontent.com/20374265/194752869-1441c654-d25b-4d74-930d-d0e63dafffe1.png)

**Comment by wgottwalt** [comment]
Sorry for the late answer, I'm a bit busy. Looks like they added the efficiency reporting from the AXi series to the new 2022 HXi series. To figure out the matching command I would need access to one of the newer power supplies or maybe a proper usb capture could already be enough. I'm aware of the fan controls and the rail switching. I left the possibility to change the values out of the mainline driver, because it could be used to damage the PSU. The driver also has debugfs entries where it reports uptimes, names and other states of the device (https://elixir.bootlin.com/linux/v6.1-rc1/source/Documentation/hwmon/corsair-psu.rst).
